//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecondMonServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.127.2")]
        public string MIS_BASE_IP_ADDRESS {
            get {
                return ((string)(this["MIS_BASE_IP_ADDRESS"]));
            }
            set {
                this["MIS_BASE_IP_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sretenka")]
        public string MIS_BASE_NAME {
            get {
                return ((string)(this["MIS_BASE_NAME"]));
            }
            set {
                this["MIS_BASE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CYCLE_INTERVAL_SECONDS {
            get {
                return ((int)(this["CYCLE_INTERVAL_SECONDS"]));
            }
            set {
                this["CYCLE_INTERVAL_SECONDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.16.127.2")]
        public string NOTIFICATION_BASE_IP_ADDRESS {
            get {
                return ((string)(this["NOTIFICATION_BASE_IP_ADDRESS"]));
            }
            set {
                this["NOTIFICATION_BASE_IP_ADDRESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sretenka")]
        public string NOTIFICATION_BASE_NAME {
            get {
                return ((string)(this["NOTIFICATION_BASE_NAME"]));
            }
            set {
                this["NOTIFICATION_BASE_NAME"] = value;
            }
        }
    }
}
